#! /bin/sh

#sxhkd -m -1 -c ~/.config/sxhkd/.sxhkdrc > ~/.local/sxhkdlog.txt 2>&1 &
panel.sh &

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a google-chrome-stable desktop=^2 state=tiled
