#!/bin/sh

# Setup wallpaper

feh --bg-scale /home/nihliphobe/images/summit_wp.jpg

python /home/nihliphobe/.config/herbstluftwm/autostart.py >> /home/nihliphobe/.config/herbstluftwm/log.txt

# Murder the bell. END IT

set bell-style visible
